services:
  dev-idp:
    build: .
    ports:
      - 7000:7000
    env_file:
      - ./container.env
    volumes:
        - ./db:/run/db
    networks:
      - default
    # Below allows for debugging with pdb etc.
    stdin_open: true
    tty: true
    secrets:
      - private_key
      - public_cert


networks:
  default:

secrets:
  private_key:
    file: ./certificates/private.key
  public_cert:
    file: ./certificates/public.cert

