# Generated by Django 4.0.8 on 2022-10-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_affiliation_name_alter_entitlement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='', help_text='In UU terminology this is the Solis-ID, thus equal to username', max_length=150, unique=True, verbose_name='uid'),
            preserve_default=False,
        ),
    ]
