# Generated by Django 4.0.8 on 2022-10-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eduPersonAffiliation',
            new_name='_eduPersonAffiliation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='eduPersonEntitlement',
            new_name='_eduPersonEntitlement',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isMemberOf',
            new_name='_isMemberOf',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='_mail',
        ),
    ]
