# Generated by Django 4.0.8 on 2022-10-12 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_edupersonaffiliation_user__edupersonaffiliation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_mail',
        ),
        migrations.AddField(
            model_name='usermail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
