# Generated by Django 4.0.8 on 2023-06-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user__mail_usermail_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='schacHomeOrganisation',
            new_name='schacHomeOrganization',
        ),
    ]
