# Generated by Django 4.0.8 on 2023-06-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_schachomeorganisation_user_schachomeorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cn',
            field=models.CharField(blank=True, max_length=150, verbose_name='common name'),
        ),
    ]
